### ISSUE TITLE
Greenkeeper.io bot

### ISSUE THREAD

**Issue by BhaveshSGupta** [BhaveshSGupta/configurable-frontend-starter-kit#14]
Suggestion needed, 
would it be wise to add greekeeper.io bot to check for dependency updates?
If yes can you help in configuring it into code base and no then can you give reasons why?

**Comment by skprabhanjan** [comment]
@BhaveshSGupta , adding greenkeeper is a good option but I think these conditions need to be met first in order to add it (https://greenkeeper.io/docs.html#prerequisites).
As I see now, CI is not provisioned yet.

**Comment by BhaveshSGupta** [comment]
@skprabhanjan, Do you want to help in setting it up?
